---
title: "Non_Explosion_graph02"
author: "Yu Jisu"
date: '2021 6 3 '
output: html_document
---

```{r}
#packages
if(!require(dplyr)) install.packages('dplyr'); require(dplyr)
if(!require(tidyr)) install.packages('tidyr'); require(tidyr)
if(!require(tidyverse)) install.packages('tidyverse'); require(tidyverse)

#directory - R_code
print(dirname(rstudioapi::getActiveDocumentContext()$path))
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

#Rdata load
load(file="../0.Data/N3_RData/info_data.Rdata")
#str(info_df)

```

```{r}


i<-1
#for (i in 0:89){
  tmp <- info_df %>% filter(File_num==i)
  Explosion_Cell <- unique(tmp[which(tmp$y=="1"),'Item_No'])
  Non_Explosion_Cell <- unique(tmp[-which(tmp$y=="1"),'Item_No'])

  tmp <- tmp[!is.na(tmp$Z.IR_Plates_mean),]
  
  tmp1 <- tmp %>% filter(Item_No == Explosion_Cell)
  hist(tmp1$Z.IR_Plates_mean,breaks=50)
  
  for (aa in Non_Explosion_Cell){
    tmp2 <- tmp %>% filter(Item_No == aa )
    hist(tmp2$Z.IR_Plates_mean,breaks=50)
  }
  
#}

```

```{r}


i<-1
#for (i in 0:89){
  tmp <- info_df %>% filter(File_num==i)
  Explosion_Cell <- unique(tmp[which(tmp$y=="1"),'Item_No'])
  Non_Explosion_Cell <- unique(tmp[-which(tmp$y=="1"),'Item_No'])

  tmp <- tmp[!is.na(tmp$Z.IR_Plates_sd),]
  
  tmp1 <- tmp %>% filter(Item_No == Explosion_Cell)
  hist(tmp1$Z.IR_Plates_sd,breaks=50)
  
  for (aa in Non_Explosion_Cell){
    tmp2 <- tmp %>% filter(Item_No == aa )
    hist(tmp2$Z.IR_Plates_sd,breaks=50)
  }
  
#}

```

```{r mean}


  tmp <- info_df[!is.na(info_df$Z.IR_Plates_mean),]
  
  tmp1 <- tmp %>% filter(y=="1")
  hist(tmp1$Z.IR_Plates_mean,breaks=1000)
  
  tmp2 <- tmp %>% filter(y!="1" )
  hist(tmp2$Z.IR_Plates_mean,breaks=1000)
  
  

```


```{r sd}


  tmp <- info_df[!is.na(info_df$Z.IR_Plates_sd),]
  
  tmp1 <- tmp %>% filter(y=="1")
  hist(tmp1$Z.IR_Plates_sd,breaks=1000)
  
  tmp2 <- tmp %>% filter(y!="1" )
  hist(tmp2$Z.IR_Plates_sd,breaks=1000)
  
  

```


```{r med}


  tmp <- info_df[!is.na(info_df$Z.IR_Plates_med),]
  
  tmp1 <- tmp %>% filter(y=="1")
  hist(tmp1$Z.IR_Plates_med,breaks=1000)
  
  tmp2 <- tmp %>% filter(y!="1" )
  hist(tmp2$Z.IR_Plates_med,breaks=1000)
  
  

```

```{r min}


  tmp <- info_df[!is.na(info_df$Z.IR_Plates_min),]
  
  tmp1 <- tmp %>% filter(y=="1")
  hist(tmp1$Z.IR_Plates_min,breaks=1000)
  
  tmp2 <- tmp %>% filter(y!="1" )
  hist(tmp2$Z.IR_Plates_min,breaks=1000)
  
  

```


```{r max}


  tmp <- info_df[!is.na(info_df$Z.IR_Plates_max),]
  
  tmp1 <- tmp %>% filter(y=="1")
  hist(tmp1$Z.IR_Plates_max,breaks=1000)
  
  tmp2 <- tmp %>% filter(y!="1" )
  hist(tmp2$Z.IR_Plates_max,breaks=1000)
  
  

```


```{r range}


  tmp <- info_df[!is.na(info_df$Z.IR_Plates_range),]
  
  tmp1 <- tmp %>% filter(y=="1")
  hist(tmp1$Z.IR_Plates_range,breaks=1000)
  
  tmp2 <- tmp %>% filter(y!="1" )
  hist(tmp2$Z.IR_Plates_range,breaks=1000)
  
  

```

